# Use your own admin credentials from a Kubernetes secret
admin:
  existingSecret: grafana

# Optional: to still define fallback values
adminUser: admin
adminPassword: admin123

# Optional UI / environment configuration
env:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin123

grafana.ini:
  users:
    default_theme: light
  server:
    root_url: http://grafana.local
