# Use your own admin credentials from a Kubernetes secret
admin:
  existingSecret: grafana

# Optional: to still define fallback values
adminUser: admin
adminPassword: admin123

# Optional UI / environment configuration
env:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin123

grafana.ini:
  users:
    default_theme: light
  server:
    root_url: http://grafana.local

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
        isDefault: true
        editable: true

      - name: Loki
        type: loki
        access: proxy
        url: http://loki.monitoring.svc:3100
        editable: true
