# Disable built-in Grafana (we’ll run our own)
grafana:
  enabled: false

# Disable Kubernetes control-plane components that fail on Docker Desktop
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
coreDns:
  enabled: false
kubeEtcd:
  enabled: false

# Disable Node Exporter (not supported in Docker Desktop)
nodeExporter:
  enabled: true
  hostNetwork: false

  # Disable host filesystem mounts that break on Docker Desktop
  hostRootFsMount:
    enabled: false

  # Use a safer security context for Docker Desktop
  service:
    port: 9100
  tolerations: []
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534  # nobody


# Optional: disable webhooks that sometimes fail locally
prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
  tls:
    enabled: false


# Prometheus core configuration
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    scrapeInterval: 15s
