apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-store
  namespace: default
  labels:
    app: mini-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-store
  template:
    metadata:
      labels:
        app: mini-store
    spec:
      containers:
      - name: mini-store
        image: ghcr.io/ealoltm/testapp:latest
        ports:
        - containerPort: 8000