apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mini-store-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: mini-store
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
