name: Argo CD Deploy (local)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy ArgoCD to local cluster
    runs-on: self-hosted
    env:
      KUBECONFIG: C:\Users\ealol\.kube\config

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ------------------------------
      # Step 1: Ensure namespace
      # ------------------------------
      - name: Ensure argocd namespace
        shell: powershell
        run: |
          Write-Host "Applying ArgoCD namespace..."
          kubectl apply -f monitoring/argocd/namespace.yaml

      # ------------------------------
      # Step 2: Install ArgoCD core components
      # ------------------------------
      - name: Install ArgoCD core
        shell: powershell
        run: |
          Write-Host "Installing ArgoCD..."
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          Write-Host "Waiting for ArgoCD server rollout..."
          kubectl -n argocd rollout status deploy/argocd-server --timeout=240s

      # ------------------------------
      # Step 3: Apply  Application
      # ------------------------------
      - name: C register Application
        shell: powershell
        run: |
          Write-Host "Applying app definition..."
          kubectl apply -f monitoring/argocd/apps/testapp.yaml
          Write-Host "Listing resources..."
          kubectl get pods -n argocd
          kubectl get svc -n argocd
          kubectl get ingress -n argocd
