name: Argo CD Deploy (local)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy ArgoCD to local cluster
    runs-on: self-hosted
    env:
      KUBECONFIG: C:\Users\ealol\.kube\config

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ------------------------------
      # Step 1: Ensure namespace exists
      # ------------------------------
      - name: Ensure argocd namespace (YAML)
        shell: bash
        run: |
          echo "Applying namespace manifest..."
          kubectl apply -f monitoring/argocd/apps/namespace.yaml

      # ------------------------------
      # Step 2: Install ArgoCD core components
      # ------------------------------
      - name: Install ArgoCD core
        shell: bash
        run: |
          echo "Installing ArgoCD..."
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          echo "Waiting for ArgoCD server rollout..."
          kubectl -n argocd rollout status deploy/argocd-server --timeout=240s || true

      # ------------------------------
      # Step 3: Apply ingress and app definitions
      # ------------------------------
      - name: Configure ingress and register Application
        shell: bash
        run: |
          echo "Applying ingress..."
          kubectl apply -f monitoring/argocd/apps/ingress.yaml
          echo "Applying testapp application..."
          kubectl apply -f monitoring/argocd/apps/testapp.yaml
          echo "Listing ArgoCD resources..."
          kubectl -n argocd get pods
          kubectl -n argocd get svc
          kubectl -n argocd get ingress

      # ------------------------------
      # Step 4: Print ArgoCD initial credentials
      # ------------------------------
      - name: Show ArgoCD Login Credentials
        shell: bash
        run: |
          echo "====================================================="
          echo "ArgoCD is ready!"
          echo "URL: http://argocd.local"
          echo "Username: admin"
          echo -n "Password: "
          kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 --decode
          echo ""
          echo "====================================================="
