name: Terraform Destroy Local Kubernetes

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-destroy:
    name: Destroy Terraform-managed resources locally
    runs-on: self-hosted

    env:
      KUBECONFIG: C:\Users\ealol\.kube\config
      TF_IN_AUTOMATION: true

    defaults:
      run:
        working-directory: terraform

    steps:
      # Step 1 — Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2 — Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # Step 3 — Initialize Terraform
      - name: Terraform Init
        run: terraform init -input=false

      # Step 4 — Import existing resources (PowerShell-friendly)
      - name: Import existing Kubernetes resources
        shell: pwsh
        run: |
          Write-Host "Attempting to import Kubernetes resources..."
          try {
            terraform import kubernetes_manifest.mini_store_deploy default/mini-store
          } catch {
            Write-Host "Deployment not found, skipping."
          }

          try {
            terraform import module.mini_store.kubernetes_service.mini_store_service default/mini-store-service
          } catch {
            Write-Host "Service not found, skipping."
          }

          try {
            terraform import module.mini_store.kubernetes_ingress_v1.mini_store_ingress default/mini-store-ingress
          } catch {
            Write-Host "Ingress not found, skipping."
          }

      # Step 5 — Plan destroy
      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=tfplan

      # Step 6 — Apply destroy (no approval)
      - name: Terraform Destroy
        run: terraform apply -auto-approve tfplan

      # Step 7 — Verify deletion (PowerShell-safe)
      - name: Verify Kubernetes cleanup
        shell: pwsh
        run: |
          try {
            kubectl get all -n default
          } catch {
            Write-Host "kubectl failed — cluster may already be empty."
          }
