name: Terraform Destroy (Auto)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-destroy:
    runs-on: self-hosted

    env:
      KUBECONFIG: C:\Users\ealol\.kube\config
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Terraform
        run: terraform version

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -input=false

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

      - name: Terraform Plan (Destroy)
        run: |
          cd terraform
          terraform plan -destroy -out=tfplan

      - name: Show Destroy Plan
        run: |
          cd terraform
          terraform show tfplan

      - name: Terraform Destroy Apply
        run: |
          cd terraform
          terraform apply -auto-approve ./tfplan
